### ISSUE TITLE
long name for a function:c

### ISSUE THREAD

**Issue by maremun** [Evfro/showprogress#1]
can you maybe change showprogress to something shorter? maybe simply show?

**Comment by evfro** [comment]
I've tried to be explicit in naming, which is a part of style guide. I believe, using `show` hides what is the exact purpose of the function.

I'd suggest using _import aliasing_, like:  
```python
from showprogress import showprogress as show
```

What do you think?

P.S. In the current implementation its not even a function but a class. This may change in the future.

**Comment by evfro** [comment]
Hi! The usage has changed. You can now import as (note that the name of the package has changed):
```python
from ipypb import track
```
This instance expects iterable as an input argument, e.g. `track(range(10))`. If you always work with python `range`, then it maybe more convenient to use
```python
from ipypb import irange
```
And if you already have a bunch of code with `range`, you may simply reassign it as `range = irange` (this is a bad practice though). Note also, that if you want to replace `tqdm_notebook` with `ipypb` in your existing code, you can quickly do it by:
```python
from ipypb import ipb
tqdm_notebook = ipb
```
This is a general factory function that gives you either `track` or `irange` depending on the input arguments. It also handles compatibility with `tqdm` arguments.
